# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54bd1b01c40bf33e3e1b7c85d08cbbea0bca3d101a114d6951ef3ca14ad55815f2e2b490bd1734b9632e739d57dc10fe919f75faa71b960d08be6248fe469047

test:
  secret_key_base: 02ca875dd6d0aa5c9914d559722a0cb6047a61f13ccce0120e542419cec9024053c05d80d34672cb334d5c7b84287e807dc70dc7b73141ea0647a1452cecced0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
